name: 'pylint-and-format'
description: 'Perform Style Checking on your Python 3 using flake8 and formate code using black'
inputs:
  filename:
    description: 'filename'
    required: true
    default: 'test.py'
branding:
  icon: 'code'
  color: 'black'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
