name: 'pylint-and-format'
description: 'Perform Style Checking on your Python 3 using flake8 and formate code using black'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
